### PR TITLE
Update to use DebugConfigurationProvider

### LINKED ISSUE #1046: VSCODE- Insiders: Timed out waiting for the PowerShell extension to start
### System Details

- Operating system name and version: Windows 10 
- VS Code version: 1.18.0 Insiders (commit date 2017-10-06T05:26:16.770Z)
- PowerShell extension version: 1.4.3
- Output from `$PSVersionTable`:  5.1.15063.632

### Issue Description

Error: Timed out waiting for the PowerShell extension to start.

This seems to be specific for latest 1.18 insiders build. All works normally on 1.17 public version.
I tried multiple computers and its the same behaviour.  
PowerShell extension is timing out when pressing F5, or trying to start any script.

image

### Steps to reproduce
- On clean Windows 10 machine install VS Code Insiders 1.18.0. 
- Install PowerShell extension v.1.4.3
- Wirite simple script (something as Write-Host 1)
- Press F5

Expected behaviour is to diplay 1 in console. But, nothing actually happens. After some time, time out error will appear.

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1362792/logs.zip)

### PR DESCRIPTION
**Pull request by rkeithhill**
Fix #1046
Fix warning in status bar about ThemeColor

This fix requires PSES PR 556 to eliminate one PSES cause of the debug adapter to crash.

Also npm generated a package-lock.json file which, from what I've read, should be checked in.  I haven't included it in this PR - yet.  Thoughts?

Also, I updated min VSCode version to 1.17.0.  I'm not sure when the new DebugConfigurationProvider API was intro'd.  I  have tested with 1.17.2 and it works there so I'm reasonably confident it will work in 1.17.0.  We might be able to reach back a bit further.  We'd have to find out when this API was intro'd.

### CODE REVIEW

**Comment by rkeithhill** [comment]
Hmm:
```
error TS2305: Module ''vscode'' has no exported member 'DebugConfigurationProvider'.
```
Maybe we just stick with a minimum of VSCode `1.17.0` then.

**Comment by daviwil** [comment]
Yep, go ahead and add package-lock.json, it's new the new standard behavior in Node 8 I think.

I suppose my only concern here is whether we ship an update later this week (I'd like to) and if this will work in VS Code 1.16.0.  Have you tried loading the built extension in that version to see if it works?

**Comment by rkeithhill** [comment]
I bumped the version down to 1.16, pushed that but one of the builds failed.  So I backed that change out.

**Comment by rkeithhill** [comment]
I'll add the package-lock.json file as soon as I get home tonight.

**Comment by rkeithhill** [comment]
Done.

**Comment by rkeithhill** [comment]
For the record, it seems the API we need only exists in 1.16.0 in the vscode.proposed.d.ts typings file.  In 1.17.0 the API appears in the vscode.d.ts file.

**Comment by daviwil** [comment]
I just tried your changes in 1.17.2, they work great! Thinking about merging this now, anything else you needed to do?

**Comment by rkeithhill** [comment]
I think this one is ready to go.

**Comment by daviwil** [comment]
Awesome, thanks a lot for fixing it!
